use hkdf::Hkdf;
use sha2::Sha256;
use thiserror::Error;
use zeroize::{Zeroize, Zeroizing};

/// PRF seed material unsealed or loaded from TPM-protected state.
#[derive(Clone)]
pub struct SecretSeed(Zeroizing<Vec<u8>>);

impl SecretSeed {
    /// Copies seed bytes into a zeroizing container.
    pub fn new(bytes: impl AsRef<[u8]>) -> Result<Self, DeriveError> {
        let bytes = bytes.as_ref();
        if bytes.is_empty() {
            return Err(DeriveError::EmptySeed);
        }
        Ok(Self(Zeroizing::new(bytes.to_vec())))
    }

    pub(crate) fn as_bytes(&self) -> &[u8] {
        &self.0
    }
}

/// Deterministic label mode or explicit entropy mode for derived operations.
#[derive(Clone, Debug, Eq, PartialEq)]
pub enum DeriveMode {
    /// Reproducible derivation for the same seed and label.
    Deterministic { label: Vec<u8> },
    /// Non-reproducible derivation. The caller supplies randomness generated by
    /// its caller so this core module stays deterministic and testable.
    Ephemeral { label: Vec<u8>, entropy: Vec<u8> },
}

impl Drop for DeriveMode {
    fn drop(&mut self) {
        match self {
            Self::Deterministic { label } => label.zeroize(),
            Self::Ephemeral { label, entropy } => {
                label.zeroize();
                entropy.zeroize();
            }
        }
    }
}

impl DeriveMode {
    /// Build deterministic derivation mode using the supplied label.
    pub fn deterministic(label: impl Into<Vec<u8>>) -> Self {
        Self::Deterministic {
            label: label.into(),
        }
    }

    /// Build ephemeral derivation mode using caller-supplied entropy.
    pub fn ephemeral(label: impl Into<Vec<u8>>, entropy: impl Into<Vec<u8>>) -> Self {
        Self::Ephemeral {
            label: label.into(),
            entropy: entropy.into(),
        }
    }

    pub(crate) fn info_prefix(&self) -> Vec<u8> {
        let mut info = Vec::new();
        match self {
            Self::Deterministic { label } => {
                info.extend_from_slice(b"mode=deterministic\0label=");
                info.extend_from_slice(label);
            }
            Self::Ephemeral { label, entropy } => {
                info.extend_from_slice(b"mode=ephemeral\0label=");
                info.extend_from_slice(label);
                info.extend_from_slice(b"\0entropy=");
                info.extend_from_slice(entropy);
            }
        }
        info
    }
}

/// Derived-key algorithm family.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum DerivedAlgorithm {
    /// NIST P-256 ECDSA key derivation.
    P256,
    /// Ed25519 signing key derivation.
    Ed25519,
    /// secp256k1 ECDSA key derivation.
    Secp256k1,
}

impl DerivedAlgorithm {
    pub(crate) fn domain(self) -> &'static [u8] {
        match self {
            Self::P256 => b"p256",
            Self::Ed25519 => b"ed25519",
            Self::Secp256k1 => b"secp256k1",
        }
    }
}

/// Requested operation over a derived software key.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum DeriveUse {
    /// Export the derived private/secret key bytes.
    Secret,
    /// Export the derived public key bytes.
    Pubkey,
    /// Sign a message or digest with the derived key.
    Sign,
}

/// Hash selector accepted by algorithms that support pre-hash semantics.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum HashSelection {
    /// SHA-256 prehash selection.
    Sha256,
    /// SHA-384 prehash selection.
    Sha384,
    /// SHA-512 prehash selection.
    Sha512,
}

/// Validated operation request.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct DeriveRequest {
    /// Algorithm family for the derived key.
    pub algorithm: DerivedAlgorithm,
    /// Operation requested for the derived key.
    pub use_: DeriveUse,
    /// Optional hash selection for ECDSA signing.
    pub hash: Option<HashSelection>,
}

impl DeriveRequest {
    /// Validate and construct a derived-key request.
    pub fn new(
        algorithm: DerivedAlgorithm,
        use_: DeriveUse,
        hash: Option<HashSelection>,
    ) -> Result<Self, DeriveError> {
        if algorithm == DerivedAlgorithm::Ed25519 && use_ == DeriveUse::Sign && hash.is_some() {
            return Err(DeriveError::HashNotAllowedForEd25519Sign);
        }
        Ok(Self {
            algorithm,
            use_,
            hash,
        })
    }
}

/// Errors produced by derived software-key primitives.
#[derive(Debug, Error, Eq, PartialEq)]
pub enum DeriveError {
    /// Seed material was empty.
    #[error("PRF seed must not be empty")]
    EmptySeed,
    /// HKDF output expansion failed.
    #[error("HKDF expansion failed")]
    HkdfExpand,
    /// No valid scalar was found before the retry limit.
    #[error("candidate scalar remained invalid after {0} attempts")]
    ScalarExhausted(u32),
    /// Ed25519 signing was requested with an external hash selection.
    #[error("Ed25519 signing does not accept --hash in v1")]
    HashNotAllowedForEd25519Sign,
    /// Caller-supplied digest was invalid for ECDSA signing.
    #[error("invalid ECDSA prehash")]
    InvalidPrehash,
}

const HKDF_SALT: &[u8] = b"tpmctl derived software key v1";
const MAX_SCALAR_ATTEMPTS: u32 = 1024;

pub(crate) fn derive_bytes(
    seed: &SecretSeed,
    mode: &DeriveMode,
    algorithm: DerivedAlgorithm,
    purpose: &[u8],
    counter: u32,
) -> Result<Zeroizing<[u8; 32]>, DeriveError> {
    let hk = Hkdf::<Sha256>::new(Some(HKDF_SALT), seed.as_bytes());
    let mut info = mode.info_prefix();
    info.extend_from_slice(b"\0algorithm=");
    info.extend_from_slice(algorithm.domain());
    info.extend_from_slice(b"\0purpose=");
    info.extend_from_slice(purpose);
    info.extend_from_slice(b"\0counter=");
    info.extend_from_slice(&counter.to_be_bytes());

    let mut out = Zeroizing::new([0_u8; 32]);
    hk.expand(&info, &mut *out)
        .map_err(|_| DeriveError::HkdfExpand)?;
    info.zeroize();
    Ok(out)
}

pub(crate) fn derive_valid_secret_key<K, F>(
    seed: &SecretSeed,
    mode: &DeriveMode,
    algorithm: DerivedAlgorithm,
    purpose: &[u8],
    mut try_key: F,
) -> Result<K, DeriveError>
where
    F: FnMut(&[u8; 32]) -> Option<K>,
{
    for counter in 0..MAX_SCALAR_ATTEMPTS {
        let candidate = derive_bytes(seed, mode, algorithm, purpose, counter)?;
        if let Some(key) = try_key(&candidate) {
            return Ok(key);
        }
    }
    Err(DeriveError::ScalarExhausted(MAX_SCALAR_ATTEMPTS))
}

#[cfg(test)]
pub(crate) fn retry_valid_candidate_for_test<K, F>(mut try_key: F) -> Result<K, DeriveError>
where
    F: FnMut(&[u8; 32]) -> Option<K>,
{
    for counter in 0..MAX_SCALAR_ATTEMPTS {
        let mut candidate = [0_u8; 32];
        candidate[31] = counter as u8;
        let candidate = Zeroizing::new(candidate);
        if let Some(key) = try_key(&candidate) {
            return Ok(key);
        }
    }
    Err(DeriveError::ScalarExhausted(MAX_SCALAR_ATTEMPTS))
}

#[cfg(test)]
#[path = "primitives.test.rs"]
mod tests;
